version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  
  deploy:
    docker:
      - image: circleci/node:10.0-browsers # < an arbitrarily chosen docker image.
    steps:
      - checkout
      - run:
          name: Trigger docker remotely
          command: curl -v -X POST https://hub.docker.com/api/build/v1/source/2b6c67d0-0be1-41b6-8952-d1e5c7cf59ee/trigger/96f10cbb-d052-481f-afc9-161e2972d250/call/

workflows:
    build-and-test-and-deploy:
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test
            filters:
              branches:
                only: master